### ISSUE TITLE
Methods with the same name as their class

### ISSUE THREAD

**Issue by jasperf** [wecodemore/wp-importer#4]
`( ! ) Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; WP_Import has a deprecated constructor in /srv/www/domain.com/current/web/app/plugins/wp-importer-master/wordpress-importer.php on line 38
`

`__construct` can be used.

**Comment by franz-josef-kaiser** [comment]
Hi @jasperf Thanks for the bug report. Can you please go to the repo page of that class, press Y for a link to the blob and update your description with it? Will then fix tomorrow and push an update.

**Comment by jasperf** [comment]
Forked your repo and created a pull request. Should work as well I think..

**Comment by franz-josef-kaiser** [comment]
@jasperf Thanks a lot for your PR! #5
